// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: operator/src/main/protobuf/Coprocessor.proto

package com.qingcloud.appcenter.hbase.coprocessor;

public final class PbCoprocessor {
  private PbCoprocessor() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CountRowRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string columnFamily = 1;
    /**
     * <code>optional string columnFamily = 1;</code>
     */
    boolean hasColumnFamily();
    /**
     * <code>optional string columnFamily = 1;</code>
     */
    java.lang.String getColumnFamily();
    /**
     * <code>optional string columnFamily = 1;</code>
     */
    com.google.protobuf.ByteString
        getColumnFamilyBytes();

    // optional string startRowKey = 2;
    /**
     * <code>optional string startRowKey = 2;</code>
     */
    boolean hasStartRowKey();
    /**
     * <code>optional string startRowKey = 2;</code>
     */
    java.lang.String getStartRowKey();
    /**
     * <code>optional string startRowKey = 2;</code>
     */
    com.google.protobuf.ByteString
        getStartRowKeyBytes();

    // optional string endRowKey = 3;
    /**
     * <code>optional string endRowKey = 3;</code>
     */
    boolean hasEndRowKey();
    /**
     * <code>optional string endRowKey = 3;</code>
     */
    java.lang.String getEndRowKey();
    /**
     * <code>optional string endRowKey = 3;</code>
     */
    com.google.protobuf.ByteString
        getEndRowKeyBytes();

    // optional int32 scanBatch = 4;
    /**
     * <code>optional int32 scanBatch = 4;</code>
     */
    boolean hasScanBatch();
    /**
     * <code>optional int32 scanBatch = 4;</code>
     */
    int getScanBatch();
  }
  /**
   * Protobuf type {@code CountRowRequest}
   */
  public static final class CountRowRequest extends
      com.google.protobuf.GeneratedMessage
      implements CountRowRequestOrBuilder {
    // Use CountRowRequest.newBuilder() to construct.
    private CountRowRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CountRowRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CountRowRequest defaultInstance;
    public static CountRowRequest getDefaultInstance() {
      return defaultInstance;
    }

    public CountRowRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CountRowRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              columnFamily_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              startRowKey_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              endRowKey_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              scanBatch_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.internal_static_CountRowRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.internal_static_CountRowRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest.class, com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<CountRowRequest> PARSER =
        new com.google.protobuf.AbstractParser<CountRowRequest>() {
      public CountRowRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CountRowRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CountRowRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string columnFamily = 1;
    public static final int COLUMNFAMILY_FIELD_NUMBER = 1;
    private java.lang.Object columnFamily_;
    /**
     * <code>optional string columnFamily = 1;</code>
     */
    public boolean hasColumnFamily() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string columnFamily = 1;</code>
     */
    public java.lang.String getColumnFamily() {
      java.lang.Object ref = columnFamily_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          columnFamily_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string columnFamily = 1;</code>
     */
    public com.google.protobuf.ByteString
        getColumnFamilyBytes() {
      java.lang.Object ref = columnFamily_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        columnFamily_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string startRowKey = 2;
    public static final int STARTROWKEY_FIELD_NUMBER = 2;
    private java.lang.Object startRowKey_;
    /**
     * <code>optional string startRowKey = 2;</code>
     */
    public boolean hasStartRowKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string startRowKey = 2;</code>
     */
    public java.lang.String getStartRowKey() {
      java.lang.Object ref = startRowKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          startRowKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string startRowKey = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStartRowKeyBytes() {
      java.lang.Object ref = startRowKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startRowKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string endRowKey = 3;
    public static final int ENDROWKEY_FIELD_NUMBER = 3;
    private java.lang.Object endRowKey_;
    /**
     * <code>optional string endRowKey = 3;</code>
     */
    public boolean hasEndRowKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string endRowKey = 3;</code>
     */
    public java.lang.String getEndRowKey() {
      java.lang.Object ref = endRowKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          endRowKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string endRowKey = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEndRowKeyBytes() {
      java.lang.Object ref = endRowKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endRowKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 scanBatch = 4;
    public static final int SCANBATCH_FIELD_NUMBER = 4;
    private int scanBatch_;
    /**
     * <code>optional int32 scanBatch = 4;</code>
     */
    public boolean hasScanBatch() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 scanBatch = 4;</code>
     */
    public int getScanBatch() {
      return scanBatch_;
    }

    private void initFields() {
      columnFamily_ = "";
      startRowKey_ = "";
      endRowKey_ = "";
      scanBatch_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getColumnFamilyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getStartRowKeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEndRowKeyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, scanBatch_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getColumnFamilyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getStartRowKeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEndRowKeyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, scanBatch_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest)) {
        return super.equals(obj);
      }
      com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest other = (com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest) obj;

      boolean result = true;
      result = result && (hasColumnFamily() == other.hasColumnFamily());
      if (hasColumnFamily()) {
        result = result && getColumnFamily()
            .equals(other.getColumnFamily());
      }
      result = result && (hasStartRowKey() == other.hasStartRowKey());
      if (hasStartRowKey()) {
        result = result && getStartRowKey()
            .equals(other.getStartRowKey());
      }
      result = result && (hasEndRowKey() == other.hasEndRowKey());
      if (hasEndRowKey()) {
        result = result && getEndRowKey()
            .equals(other.getEndRowKey());
      }
      result = result && (hasScanBatch() == other.hasScanBatch());
      if (hasScanBatch()) {
        result = result && (getScanBatch()
            == other.getScanBatch());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasColumnFamily()) {
        hash = (37 * hash) + COLUMNFAMILY_FIELD_NUMBER;
        hash = (53 * hash) + getColumnFamily().hashCode();
      }
      if (hasStartRowKey()) {
        hash = (37 * hash) + STARTROWKEY_FIELD_NUMBER;
        hash = (53 * hash) + getStartRowKey().hashCode();
      }
      if (hasEndRowKey()) {
        hash = (37 * hash) + ENDROWKEY_FIELD_NUMBER;
        hash = (53 * hash) + getEndRowKey().hashCode();
      }
      if (hasScanBatch()) {
        hash = (37 * hash) + SCANBATCH_FIELD_NUMBER;
        hash = (53 * hash) + getScanBatch();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CountRowRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.internal_static_CountRowRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.internal_static_CountRowRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest.class, com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest.Builder.class);
      }

      // Construct using com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        columnFamily_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        startRowKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        endRowKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        scanBatch_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.internal_static_CountRowRequest_descriptor;
      }

      public com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest getDefaultInstanceForType() {
        return com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest.getDefaultInstance();
      }

      public com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest build() {
        com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest buildPartial() {
        com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest result = new com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.columnFamily_ = columnFamily_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.startRowKey_ = startRowKey_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.endRowKey_ = endRowKey_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.scanBatch_ = scanBatch_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest) {
          return mergeFrom((com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest other) {
        if (other == com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest.getDefaultInstance()) return this;
        if (other.hasColumnFamily()) {
          bitField0_ |= 0x00000001;
          columnFamily_ = other.columnFamily_;
          onChanged();
        }
        if (other.hasStartRowKey()) {
          bitField0_ |= 0x00000002;
          startRowKey_ = other.startRowKey_;
          onChanged();
        }
        if (other.hasEndRowKey()) {
          bitField0_ |= 0x00000004;
          endRowKey_ = other.endRowKey_;
          onChanged();
        }
        if (other.hasScanBatch()) {
          setScanBatch(other.getScanBatch());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string columnFamily = 1;
      private java.lang.Object columnFamily_ = "";
      /**
       * <code>optional string columnFamily = 1;</code>
       */
      public boolean hasColumnFamily() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string columnFamily = 1;</code>
       */
      public java.lang.String getColumnFamily() {
        java.lang.Object ref = columnFamily_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          columnFamily_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string columnFamily = 1;</code>
       */
      public com.google.protobuf.ByteString
          getColumnFamilyBytes() {
        java.lang.Object ref = columnFamily_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          columnFamily_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string columnFamily = 1;</code>
       */
      public Builder setColumnFamily(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        columnFamily_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string columnFamily = 1;</code>
       */
      public Builder clearColumnFamily() {
        bitField0_ = (bitField0_ & ~0x00000001);
        columnFamily_ = getDefaultInstance().getColumnFamily();
        onChanged();
        return this;
      }
      /**
       * <code>optional string columnFamily = 1;</code>
       */
      public Builder setColumnFamilyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        columnFamily_ = value;
        onChanged();
        return this;
      }

      // optional string startRowKey = 2;
      private java.lang.Object startRowKey_ = "";
      /**
       * <code>optional string startRowKey = 2;</code>
       */
      public boolean hasStartRowKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string startRowKey = 2;</code>
       */
      public java.lang.String getStartRowKey() {
        java.lang.Object ref = startRowKey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          startRowKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string startRowKey = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStartRowKeyBytes() {
        java.lang.Object ref = startRowKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startRowKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string startRowKey = 2;</code>
       */
      public Builder setStartRowKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        startRowKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string startRowKey = 2;</code>
       */
      public Builder clearStartRowKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        startRowKey_ = getDefaultInstance().getStartRowKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string startRowKey = 2;</code>
       */
      public Builder setStartRowKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        startRowKey_ = value;
        onChanged();
        return this;
      }

      // optional string endRowKey = 3;
      private java.lang.Object endRowKey_ = "";
      /**
       * <code>optional string endRowKey = 3;</code>
       */
      public boolean hasEndRowKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string endRowKey = 3;</code>
       */
      public java.lang.String getEndRowKey() {
        java.lang.Object ref = endRowKey_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          endRowKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string endRowKey = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEndRowKeyBytes() {
        java.lang.Object ref = endRowKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endRowKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string endRowKey = 3;</code>
       */
      public Builder setEndRowKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        endRowKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string endRowKey = 3;</code>
       */
      public Builder clearEndRowKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        endRowKey_ = getDefaultInstance().getEndRowKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string endRowKey = 3;</code>
       */
      public Builder setEndRowKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        endRowKey_ = value;
        onChanged();
        return this;
      }

      // optional int32 scanBatch = 4;
      private int scanBatch_ ;
      /**
       * <code>optional int32 scanBatch = 4;</code>
       */
      public boolean hasScanBatch() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 scanBatch = 4;</code>
       */
      public int getScanBatch() {
        return scanBatch_;
      }
      /**
       * <code>optional int32 scanBatch = 4;</code>
       */
      public Builder setScanBatch(int value) {
        bitField0_ |= 0x00000008;
        scanBatch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 scanBatch = 4;</code>
       */
      public Builder clearScanBatch() {
        bitField0_ = (bitField0_ & ~0x00000008);
        scanBatch_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CountRowRequest)
    }

    static {
      defaultInstance = new CountRowRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CountRowRequest)
  }

  public interface CountRowResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 count = 1;
    /**
     * <code>required int64 count = 1;</code>
     */
    boolean hasCount();
    /**
     * <code>required int64 count = 1;</code>
     */
    long getCount();
  }
  /**
   * Protobuf type {@code CountRowResponse}
   */
  public static final class CountRowResponse extends
      com.google.protobuf.GeneratedMessage
      implements CountRowResponseOrBuilder {
    // Use CountRowResponse.newBuilder() to construct.
    private CountRowResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CountRowResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CountRowResponse defaultInstance;
    public static CountRowResponse getDefaultInstance() {
      return defaultInstance;
    }

    public CountRowResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CountRowResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              count_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.internal_static_CountRowResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.internal_static_CountRowResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse.class, com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<CountRowResponse> PARSER =
        new com.google.protobuf.AbstractParser<CountRowResponse>() {
      public CountRowResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CountRowResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CountRowResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 count = 1;
    public static final int COUNT_FIELD_NUMBER = 1;
    private long count_;
    /**
     * <code>required int64 count = 1;</code>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 count = 1;</code>
     */
    public long getCount() {
      return count_;
    }

    private void initFields() {
      count_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, count_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, count_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse)) {
        return super.equals(obj);
      }
      com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse other = (com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse) obj;

      boolean result = true;
      result = result && (hasCount() == other.hasCount());
      if (hasCount()) {
        result = result && (getCount()
            == other.getCount());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasCount()) {
        hash = (37 * hash) + COUNT_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getCount());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CountRowResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.internal_static_CountRowResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.internal_static_CountRowResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse.class, com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse.Builder.class);
      }

      // Construct using com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        count_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.internal_static_CountRowResponse_descriptor;
      }

      public com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse getDefaultInstanceForType() {
        return com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse.getDefaultInstance();
      }

      public com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse build() {
        com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse buildPartial() {
        com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse result = new com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.count_ = count_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse) {
          return mergeFrom((com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse other) {
        if (other == com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse.getDefaultInstance()) return this;
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCount()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 count = 1;
      private long count_ ;
      /**
       * <code>required int64 count = 1;</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 count = 1;</code>
       */
      public long getCount() {
        return count_;
      }
      /**
       * <code>required int64 count = 1;</code>
       */
      public Builder setCount(long value) {
        bitField0_ |= 0x00000001;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 count = 1;</code>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CountRowResponse)
    }

    static {
      defaultInstance = new CountRowResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CountRowResponse)
  }

  /**
   * Protobuf service {@code CountService}
   */
  public static abstract class CountService
      implements com.google.protobuf.Service {
    protected CountService() {}

    public interface Interface {
      /**
       * <code>rpc countRow(.CountRowRequest) returns (.CountRowResponse);</code>
       */
      public abstract void countRow(
          com.google.protobuf.RpcController controller,
          com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest request,
          com.google.protobuf.RpcCallback<com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new CountService() {
        @java.lang.Override
        public  void countRow(
            com.google.protobuf.RpcController controller,
            com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest request,
            com.google.protobuf.RpcCallback<com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse> done) {
          impl.countRow(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.countRow(controller, (com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc countRow(.CountRowRequest) returns (.CountRowResponse);</code>
     */
    public abstract void countRow(
        com.google.protobuf.RpcController controller,
        com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest request,
        com.google.protobuf.RpcCallback<com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.countRow(controller, (com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest)request,
            com.google.protobuf.RpcUtil.<com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void countRow(
          com.google.protobuf.RpcController controller,
          com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest request,
          com.google.protobuf.RpcCallback<com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse.class,
            com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse countRow(
          com.google.protobuf.RpcController controller,
          com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse countRow(
          com.google.protobuf.RpcController controller,
          com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.qingcloud.appcenter.hbase.coprocessor.PbCoprocessor.CountRowResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:CountService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CountRowRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CountRowRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CountRowResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CountRowResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,operator/src/main/protobuf/Coprocessor" +
      ".proto\"b\n\017CountRowRequest\022\024\n\014columnFamil" +
      "y\030\001 \001(\t\022\023\n\013startRowKey\030\002 \001(\t\022\021\n\tendRowKe" +
      "y\030\003 \001(\t\022\021\n\tscanBatch\030\004 \001(\005\"!\n\020CountRowRe" +
      "sponse\022\r\n\005count\030\001 \002(\0032?\n\014CountService\022/\n" +
      "\010countRow\022\020.CountRowRequest\032\021.CountRowRe" +
      "sponseBB\n)com.qingcloud.appcenter.hbase." +
      "coprocessorB\rPbCoprocessorH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CountRowRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CountRowRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CountRowRequest_descriptor,
              new java.lang.String[] { "ColumnFamily", "StartRowKey", "EndRowKey", "ScanBatch", });
          internal_static_CountRowResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_CountRowResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CountRowResponse_descriptor,
              new java.lang.String[] { "Count", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
